version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(MajorVersion)$(MinorVersion)$(PatchLevel).$(APPVEYOR_BUILD_VERSION).*'
  assembly_file_version: '$(MajorVersion).$(MinorVersion).$(PatchLevel).$(APPVEYOR_BUILD_VERSION)'
environment:
  MajorVersion: '2'
  MinorVersion: '0'
  PatchLevel: '0'
  PfxPassword:
    secure: MoBSjfTA4dQsMSor6Lbst6kKjVNAYE5elSDK6+IrR1VhCTz5yAsjBbcUC4L4SAegHKABXov/4VyL+3KtrBS8shCkgAFfSK1j98Yvn5K3JyE=
before_build:
- ps: >-
    cd $env:APPVEYOR_BUILD_FOLDER\src\

    nuget restore
build:
  project: '\src\wacs.sln'
  verbosity: minimal
after_build:
- ps: >-
    cd $env:APPVEYOR_BUILD_FOLDER\build\

    .\create-artifacts.ps1 $env:APPVEYOR_BUILD_FOLDER "$env:MajorVersion.$env:MinorVersion.$env:PatchLevel.$env:APPVEYOR_BUILD_VERSION" $env:PfxPassword

    Get-ChildItem $env:APPVEYOR_BUILD_FOLDER\build\artifacts\ | Foreach-Object {
        Push-AppveyorArtifact $_.FullName -FileName $_.Name
    }
deploy: off