version: 1.0.{build}
clone_depth: 5
install:
- git submodule update --init --recursive
- nuget restore letsencrypt-win\letsencrypt-win.sln
- nuget restore letsencrypt-win-simple.sln
build:
  project: letsencrypt-win-simple.sln
  verbosity: minimal
artifacts:
- path: letsencrypt-win-simple\bin\debug
  name: letsencrypt-win-simple
  type: zip