image: Visual Studio 2017
version: 1.0.{build}

configuration: Release

before_build:
  - nuget restore

build:
  project: win-acme.sln
  verbosity: normal

artifacts:
  - path: letsencrypt-win-simple\bin\$(CONFIGURATION)
    name: win-acme-$(CONFIGURATION)-$(APPVEYOR_BUILD_NUMBER)
    type: zip

cache:
  - packages -> **\packages.config
