theme: jekyll-theme-merlot
show_downloads: true
google_analytics: UA-134924634-2

docs_list_title: Menu
docs:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
